ABItype.cpp
CloneManager.cpp
GenBank.cpp
PrimerDesign.cpp
SendHTTP.cpp
TClone.cpp
TPhylip.cpp

I today compiled GENtle on my Mac with the clang++ it ships and was pointed to those missing []s in the corresponding deletes of what was allocated as an array.

Matching new []s with delete

---

MiscDialogs.cpp
SequenceCanvas.cpp

The ones in MiscDialogs imho are indeed bugs that clang surfaced (https://en.cppreference.com/w/cpp/language/operator_precedence) .

Avoiding warnings on operator precedence

---

ureadseq.c

Description: Fix printf and scanf format codes to match the types actually passed
Author: Olly Betts <olly@survex.com>
Last-Update: 2014-06-08
Bug-Debian: http://bugs.debian.org/750906
This is mostly about longs being used, so %d -> %ld in the format strings.

Debian's fix-format-codes patch

---

MyFrame.cpp

Avoiding backslashes in Linux and MacOS for the path to help.

Debian's forward_slashes patch

---

PCR_Troubleshoot.cpp
PCR_Troubleshoot.h
PlasmidCanvasHandlers.cpp

The get_matches function lacks a return value but is also never called, so for now this is just some trouble-causing dead code that was commented out.

Debian's YetAnotherMissingReturn patch

---

MyFrame.cpp

Nothing dramatic, it is just that I had substituted the modal marker.txt message box with a wxPrintf.

Debian's DoNotShowBoxAboutMarkersLoading patch

---

OnlineTools.cpp

With g++ it all compiles happily on Linux, but the mac using clang ran into the following:
```
OnlineTools.cpp:277:29: warning: adding 'bool' to a string does not append to the string [-Wstring-plus-int]
url += _T("&circular=") + child->vec->isLinear() ? _T("0") : _T("1") ;
~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
OnlineTools.cpp:277:29: note: use array indexing to silence this warning
url += _T("&circular=") + child->vec->isLinear() ? _T("0") : _T("1") ;
^
&                [                       ]
OnlineTools.cpp:277:54: warning: operator '?:' has lower precedence than '+'; '+' will be evaluated first [-Wparentheses]
url += _T("&circular=") + child->vec->isLinear() ? _T("0") : _T("1") ;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
OnlineTools.cpp:277:54: note: place parentheses around …
```

Fixing clang warning indicating operator precedence issue

---

main.h

A reminder to discuss the coding style.

clang: warns about nested comments

---

SequenceTypeDNA.cpp
SequenceTypeRestriction.cpp

```
SequenceTypeDNA.cpp:311:65: warning: for loop has empty body [-Wempty-body]
for ( a = 0 ; a < b && a < s.length() ; a += itemsperline ) ;
^
SequenceTypeDNA.cpp:311:65: note: put the semicolon on a separate line to silence this warning
```
Addressed first commit. a is reassigned another value without being read - this loop has no effect and was removed.
```
SequenceTypeRestriction.cpp:84:59: warning: for loop has empty body [-Wempty-body]
for ( n = 0 ; n < csgc && can->seq[n] != this ; n++ ) ;
^
SequenceTypeRestriction.cpp:84:59: note: put the semicolon on a separate line to silence this warning
```
Addressed in second commit. Semicolon was placed in line below.

Addressed clang warnings on "for loop has empty body"

---

ureadseq.c

ureadseq.c:513:10: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
if (si = strstr(V->seqid,"  Length: ")) *si = 0;
~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ureadseq.c:513:10: note: place parentheses around the assignment to silence this warning
if (si = strstr(V->seqid,"  Length: ")) *si = 0;
^
(                                 )
ureadseq.c:513:10: note: use '==' to turn this assignment into an equality comparison
if (si = strstr(V->seqid,"  Length: ")) *si = 0;
^
==
ureadseq.c:514:15: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
else if (si = strstr(V->seqid,"..")) *si = 0;
~~~^~~~~~~~~~~~~~~~~~~~~~~
ureadseq.c:514:15: note: place parentheses around the assignment to silence this warning
else if (si …

Addressed warnings by clang on assignments as conditions

---

SCFtype.cpp
SCFtype.h
TVirtualGel.cpp
main.cpp
main.h

txt() now returns a const wxString, which eliminates the warnings.
clang found extra missing []s at delete for an early return from a function.

Revisiting clang warnings

---

.github/workflows/c-cpp.yml
autogen.sh
configure.ac

Motivated by conda packaging. tinyxml.h was not found with a prefix other than /usr .

configure.ac: extend init, -I$PREFIX/include

---

Alignment.cpp

When I introduced size_t and long for positions, this had an effect on format specifications with wxPrintf and elsewhere.

Adjusted format string int -> long for size

---

RestrictionEnzymes.cpp
RestrictionEnzymes.h

No functional changes intended in this PR, supported by introduction by const keywords.
Efficiency may be slightly improved by introducing passes by reference.
As you may guess - these changes where only a side-effect, the problem I was hunting down was somewhere else.

RestrictionEnzymes.*: Introduced 'const', optics.

---

configure.ac

The error message was:
error: invalid argument '-std=gnu++11' not allowed with 'C'

Fixing compiler error for C code because of C++ standard settings.

---

TCalculator.cpp

It looked wrong not to use the symbol µ for 10^-6.

calculator micro -> µ

---

TVector.cpp
TVector.h

That took a while to hunt down,
```int l_mod = l - (rt - f) + 1 ;```
missed the parentheses. That often (not always) affected the items when performing doRemoval.
Introduced also some more passes by reference, and the usual whitespace.
I'll see what I will do with all those debug messages.

Fixed segfault in TVector upon adding feature as seq

---

.github/workflows/c-cpp.yml
ExternalBLAST.cpp
ExternalInterface.cpp
ExternalInterface.h
ExternalNCBI.cpp
INSTALL

This PR reinstates the NCBI web interface by using https instead of http, which is a bit tricky with wxWidgets. Because of a need to pass an object that could accept events, the code could not just substitute the SendHTTP routines. Fixes issue https://github.com/GENtle-persons/gentle-m/issues/66. 
The retrieval of papers and sequences does work just fine (looks nice!). Blast yet failed.

Transition NCBI+Blast to https (smoe:fix_https_query)

---

docs/manual.adoc

Copied and extended section on markers from GENtle's WikiBook page, which was not yet available from the mnanual.  Also found and added the section on requested features, pointing to GENtle's issues page on GitHub as a presumed favorable location for such requests and their discussion.

docs: Added markers section to manual.

---

RestrictionEnzymes.cpp
TRestrictionIdentifier.cpp
TVirtualGel.cpp
TVirtualGel.h

It did not crash, but a good fraction of the widgets were stacked at the upper-left corner. And when fragments of sequences were to be displayed, then GENtle ran into an assert of wxWidgets because of a double-placement.

Fix display of restriction identifiers

---

.github/workflows/c-cpp.yml

I am still somewhat uncertain about where this is all heading, but if this works as anticipated then the binary built with the CI can be accessed via the workflow that executed the build. GitHub's Ubuntu image is too old for GENtle to build because of wxWidgets, but the MacOS' binary should be fine. If this works then at some point Ubuntu should be back and also an automated cross-building for Windows should be possible.

github: Introducing workflow artifact

---

.github/workflows/codeql.yml

The distinction of setups for individual OS was not working - now with a sole focus on the MacOS and brew.

codeql: Explicitly running on MacOS for now

---

.github/workflows/c-cpp.yml
Makefile.am

codon_catalog.csv is referenced from the source tree but not redistributed.

distribution: Added codon table to list of files

---

CloningAssistant.cpp
CloningAssistant.h
MyChild.cpp
SCFtype.cpp
SCFtype.h
SequenceCanvas.h
SequenceTypePlot.cpp
TPhyloTree.cpp
TPhyloTree.h
TSequencerData.h
TUReadSeq.cpp
TUReadSeq.h
TVectorEditorItems.cpp
ipc/ipc.cpp
ureadseq.c
ureadseq.h

It started with a complaint by codeql about types, and in the age of RNA-seq I wanted the schema to allow to describe a fasta file beyond |shorts|. Have not tested if this affects the alignments (should not be the case), but I have not yet worked on the alignments anyway and with all the advents of additional tools over the last years I already know this will need some extra care - and extra tests.
Also addressed complains about working on uninitialized strings - have not checked the logic but just assingned empty strings to sid and sid1.

Codeql fix: rare memory leak, #seqs now size_t for readSeq

---

src/PlasmidCanvasLinear.cpp
src/ProgramOptionsDialog.cpp
src/TRestrictionEditor.cpp
src/TRestrictionEditor.h
src/TStorage.cpp
src/TVector.cpp
src/TVectorEditor.cpp
src/TVectorEditor.h
src/TVectorEditorEnzymes.cpp

The "Current Enzymes" list was empty upon reopening the Enzyme Management window. The enzyme list is now static, so the information is preserved across multiple openings.
Also, many debug outputs were removed.

feature+fix: min/max constraints, current enzymes now static (smoe: addressing_restriction_enzymes)
