SequenceTypeAA.cpp
SequenceTypes.cpp
TRestrictionEditor.cpp
ipc/ipc.cpp

Only introducing an assert in case that code is reached - which also quiets the compiler.

Avoid return without value in non-void function

---

README.md

Introducing README.md

---

ureadseq.c

This patch addresses compiler warnings about strcpy's destination being too small to accomodate the source. The exact sizes are subject for a review as today's sequence names may be very long.

Debian's strcpy_unreserved patch

---

Alignment.cpp
AminoAcids.cpp
CGview.cpp
ChildBase.cpp
CloningAssistant.cpp
ExternalBLAST.cpp
ManageDatabase.cpp
MyChild.cpp
MyFrame.cpp
PCR_Troubleshoot.cpp
PrimerDesign.cpp
SequenceCanvas.cpp
SequenceTypeAAstructure.cpp
SequenceTypePlot.cpp
TCalculator.cpp
TClone.h
TGraphDisplay.cpp
TImageDisplay.cpp
TPhyloTree.cpp
TRestrictionEditor.cpp
TStorage.cpp
TVectorEditor.cpp
TVectorEditorEnzymes.cpp
TVirtualGel.cpp
TXMLfile.cpp
main.cpp

Two patches contributed by Debian's volunteers outside Debian Med, likely in their role of contributors to the Debian packaging of wxWidgets when that package was earmarked to transition to a newer version.
This PR is against a new branch wxWidgets3-transition, thus without larger risks to accept, still leaving a window for other wxWidgets-independent patches to be integrated.

wxWidgets3 transition

---

.editorconfig

The tab size of 4 is set, and the presumed preference of tabs over spaces.

Added .editorconfig file - to autoconfig editors.

---

SequenceCanvas.cpp
ipc/element.cpp
ipc/element.h
ipc/pars.cpp
ipc/pars.h
ncoils.cpp
ureadseq.c

Unused variables, loss in precision (long -> int), unused pointer dereferences.

xcode: reacting to warnings

---

.editorconfig

Along suggestions from https://editorconfig.org/ .
Checked a few files with VSCode and those were fine.

Extending editorconfig

---

ChildBase.cpp
ChildBase.h
ManageDatabase.cpp
ManageDatabase.h
MyFrame.cpp
TAlignmentDialog.cpp
TStorage.cpp
TStorage.h

The transition of wxWidgets 3.0 to 3.2 it was that apparently brought in many constraints on sizers and their association with the right widget. Took me a while to identify the culprit.
The errors on sizers appear for about every dialog box, so ideally there are many more patches to come. This patch would be a candidate to be backported to the 2.x branch of GENtle.

Open box sizer adjustment

---

docs/GENtle.1
main.cpp

Also transferred man page from Debian and added that information to it.
This PR was triggered by https://github.com/GENtle-persons/gentle-m/issues/45 .

Allow GENTLE_HOMEDIR evironment variable to set homedir

---

TVector.cpp
TVector.h

As announced in https://github.com/GENtle-persons/gentle-m/pull/47#issuecomment-1792336057 .

Compile error about const TVector variable executing non-const function

---

TStorage.cpp
main.cpp

This is an important one. GENtle performs a change of the working directory to its homedir with the consequence that other relative paths, including the path to its homedir, were no longer valid.

Using only absolute path names.

---

ProgramOptionsDialog.cpp
ProgramOptionsDialog.h
RestrictionEnzymes.h
TVector.cpp
TVector.h
TVectorTree.cpp
TVectorTree.h

wxWidgets crashed over Red() not being a valid value.

Fix Crash - Settings window could not get over uninitialized colors

---

Alignment.cpp
ExternalInterface.cpp
ManageDatabase.cpp
ManageDatabase.h
MyChild.cpp
MyChild.h
MyFrame.cpp
ProgramOptionsDialog.cpp
RestrictionEnzymes.cpp
TRestrictionEditor.cpp
TRestrictionEditor.h
TRestrictionIdentifier.cpp
TVector.cpp
TVectorEditor.cpp
TVirtualGel.cpp
TVirtualGel.h
main.cpp

The assert is explained on https://docs.wxwidgets.org/3.0/classwx_string.html .
Solved by assigning string's first value to an "auto" variable.
More on white space, more passing strings by reference.

Fixed wxWidgets assert - imposed wide char on char

---

PlasmidCanvas.cpp
PlasmidCanvas.h
PlasmidCanvasCircular.cpp
PlasmidCanvasHandlers.cpp
PlasmidCanvasLinear.cpp
TUndo.cpp
TUndo.h

Just a quick early fix for
https://github.com/GENtle-persons/gentle-m/issues/63
so the figure in the manual can be reproduced. And that looks fine.
Did not yet try to understand what is going on. The second invocation of DrawPolygons triggers the error.

Avoid wxWidgets assert on single-corner polygons.

---

TGraph.cpp
TGraph.h
TGraphDisplay.cpp
TGraphScale.cpp
TLigationDialog.cpp
TLigationDialog.h
TPrimer.cpp
TPrimer.h
TProteolysis.cpp
TProteolysis.h
TRestrictionEditor.cpp
TRestrictionEditor.h
TXMLfile.cpp
TXMLfile.h

Confident that no harm was done by this patch. Please have a look at
https://github.com/GENtle-persons/gentle-m/blob/d3a389495cd14aaf4ef5229c358ce916e52b1571/TGraphDisplay.cpp#L316
which may be an incomplete commenting-out of an if-block that affects the cnt variable.

Whitespace, introduced few const declarations

---

CloneManager.cpp
MyFrame.cpp
MyFrame.h
PlasmidCanvasLinear.cpp
PrimerDesign.cpp
PrimerDesign.h
ProgramOptionsDialog.cpp
TClone.cpp
TGraph.cpp
TMainTree.cpp
TPDB.cpp
TPDB.h
TPrimer.cpp
TPrimerDialog.cpp
TProteolysis.cpp
TRestrictionEditor.cpp
TSilmutDialog.cpp
TSilmutDialog.h
TStoreAllDialog.cpp
TUReadSeq.cpp
TUReadSeq.h
TVectorEditor.cpp
TVectorEditor.h
TVectorEditorEnzymes.cpp
TVectorEditorItems.cpp
TVirtualGel.cpp
TVirtualGel.h
TextImportDialog.cpp
main.cpp
main.h

Also remove a few terminal blanks. I just wish there was an option for GNU indent for this particular formatting style :)

optics: removed tabs, introduced const

---

docs/manual.adoc

Letters before the vertical bar have special meanings in asciidoc.
The many references to the Wiki book are meant as something transitional. I just do not yet know what to transition to.

Introducing internal references. Fixing syntax of tables.

---

MyChild.cpp
SequenceCanvas.cpp
TIMGreader.cpp
ipc/ipc.cpp
ipc/pars.cpp
ipc/pars.h
main.h

Always assigning NULL to what previously pointed to the now deleted object.

CodeQL: Attempt to avoid false positives.

---

src/AminoAcids.cpp
src/SequenceTypePlot.cpp
src/TCalculator.cpp
src/TPrimer.cpp
src/TProteolysis.cpp
src/TVector.cpp
src/TVector.h
src/TVectorEditorItems.cpp

Meant to eventually help with testing.

Some methods in TVector are static.

---

src/SequenceCanvas.cpp
src/SequenceCanvas.h
src/SequenceTypeDNA.cpp

Fixes annoying crash upon selection of nucleotides. Also some indenting.

Fix: by incomplete spec of const methods

---

.github/workflows/c-cpp.yml
.github/workflows/codeql.yml

Reacting to earlier build error.

CI: arm64 update

---

src/TRestrictionEditor.cpp
src/TRestrictionEditor.h
src/TSilmutDialog.cpp
src/TSilmutDialog.h
src/TStoreAllDialog.h
src/TUndo.cpp
src/TUndo.h

Cannot reproduce prior reproducible crash when performing ligation of two sequences.

Optics - seems to also have fixed bug performing ligase

---

src/CGview.cpp
src/CGview.h
src/GenBank.cpp
src/GenBank.h
src/ManageDatabase.cpp
src/ManageDatabase.h
src/MiscDialogs.cpp
src/MiscDialogs.h
src/MyFrame.cpp
src/RestrictionEnzymes.cpp
src/RestrictionEnzymes.h
src/SCFtype.cpp
src/SequenceCanvas.cpp
src/SequenceCanvas.h
src/SequenceTypeAA.cpp
src/SequenceTypeDNA.cpp
src/SequenceTypeFeature.cpp
src/SequenceTypePlot.cpp
src/SequenceTypeRestriction.cpp
src/SequenceTypes.cpp
src/TEliteLaChromLogDialog.cpp
src/TItemEditDialog.cpp
src/TItemEditDialog.h
src/TLigationDialog.cpp
src/TPrimerDialog.cpp
src/TVector.cpp
src/TVector.h
src/enums.h
src/main.cpp
src/main.h

The automated builds should work again with wxWidgets 3.2.5 - we'll see.
A series of smaller changes that were triggered after observing a crash. That crash is gone, hoping not to have triggered too many new ones.

Ligation - eliminated crash, more on const, also const -> static

---

src/MyChild.cpp
src/MyChild.h
src/MyFrame.cpp

Spotted by accident. Got the impression that this actually improves the responsiveness :-)

Avoid immediate deletion of new vector in mychild init

---

src/Alignment.cpp
src/Alignment.h
src/SequenceCanvas.h
src/SequenceTypeABI.cpp

Passing strings by reference in backtracking.
The previous push happend prior to the commit. But here it now comes. The
```
delete [] matrix0 ;
delete [] matrix1 ;
```
I expect to make a bit of a difference.

Alignments: Code review, introducing const

---

src/Alignment.cpp
src/Alignment.h

ClustalW is increasingly rare, a more modular rewrite of that external tools interface needs to wait.

alignment: rendering self-implemented smith-waterman the default

---

src/ABIviewer.cpp
src/AminoAcids.cpp
src/MyChild.cpp
src/MyFrame.cpp
src/PCR_Troubleshoot.cpp
src/PlasmidCanvas.cpp
src/PlasmidCanvasCircular.cpp
src/PlasmidCanvasLinear.cpp
src/PrimerDesign.cpp
src/SequenceCanvas.cpp
src/TDotPlot.cpp
src/TGraphScale.cpp
src/TIMGreader.cpp
src/TImageDisplay.cpp
src/TMainTree.cpp
src/TPrimerDialog.cpp
src/TProteolysis.cpp
src/TSilmutDialog.cpp
src/TVirtualGel.cpp
src/main.h

The problem was in a selected font size 0 for printing, while hunting that down I have also eliminated use of MYFONT makro.
Fixes https://github.com/GENtle-persons/gentle-m/issues/109 .

Fix: Printing assert

---

src/CGview.cpp
src/CGview.h
src/ChildBase.cpp
src/ChildBase.h
src/FindSequenceDialog.cpp
src/ManageDatabase.cpp
src/MyFrame.cpp
src/PlasmidCanvas.cpp
src/PlasmidCanvas.h
src/SequenceCanvas.cpp
src/TClone.cpp
src/TClone.h
src/TGraph.cpp
src/TPrimer.cpp
src/TProteolysis.cpp
src/TVector.cpp
src/TVector.h

What "git stash pop" came up with.

misc: indenting, const

---

src/MyFrame.cpp
src/MyFrame.h
src/PCR_Troubleshoot.h
src/PrimerDesign.cpp
src/ProgramOptionsDialog.cpp
src/ProgramOptionsDialog.h
src/RestrictionEnzymes.cpp
src/RestrictionEnzymes.h
src/SequenceCanvas.cpp
src/SequenceTypeAA.cpp
src/TClone.cpp
src/TClone.h
src/TLigationDialog.cpp
src/TRestrictionEditor.cpp
src/TRestrictionEditor.h
src/TRestrictionIdentifier.cpp
src/TStorage.cpp
src/TStorage.h
src/TVector.cpp
src/TVector.h
src/TVectorEditor.cpp
src/TVectorEditor.h
src/TVectorEditorEnzymes.cpp

Also fixed builds on Linux fixing typo in font management. And it
fixes: https://github.com/GENtle-persons/gentle-m/issues/48
This is just an interim push, need to figure out why the "current" selection no longer works and there is an infinite loop when performing the restrictions upon pressing the "Done" button.

fix: Restriction enzymes' sequence was not set

---

src/ProgramOptionsDialog.cpp
src/SequenceTypeAA.cpp
src/TVectorEditor.cpp

Removing wxPrintf statements for what shall be tagged as another alpha release.

feature: Removing debug warnings/comments
